service: iac-qldb-univo
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  logRetentionInDays: 7
  tracing:
    apiGateway: true
    lambda: true
  environment:
    LOG_lEVEL: INFO
    POWERTOOLS_LOGGER_SAMPLE_RATE: 0.2
    POWERTOOLS_METRICS_NAMESPACE: iac-qldb-univo
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    LEDGER_NAME:
      Ref: qldbLedger
    iam:
      role:
        statements:
          - Effect: Allow
            Action:
              - qldb:SendCommand
            Resource:
              - !Sub "arn:aws:qldb:${AWS::Region}:${AWS::AccountId}:ledger/iac-qldb-univo-${self:provider.stage}"
          - Effect: Allow
            Action:
              - "array:PutTraceSegments"
              - "array:PutTelemetryRecords"
            Resource: "*"

plugins: 
  - serverless-iam-roles-per-function
  - serverless-esbuild

functions:
  createTable:
    name: qldb-sufragios-table-${self:provider.stage}
    handler: src/handlers/qldbTable.handler
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - qldb:PartiQLCreateTable
        Resource:
          - !Sub "arn:aws:qldb:${AWS::Region}:${AWS::AccountId}:ledger/iac-qldb-univo-${self:provider.stage}/*"
    memorySize: 256
    timeout: 6
    environment:
      TABLE_NAME: Sufragios

resources:
  Resources:
    qldbLedger:
      Type: AWS::QLDB::Ledger
      Properties:
        Name: iac-qldb-univo-${self:provider.stage}
        DeletionProtection: false
        PermissionsMode: STANDARD
        Tags:
          - Key: name
            Value: iac-qldb-univo

    qldbTable:
      Type: Custom::qldbTable
      DependsOn: qldbLedger
      Properties:
        ServiceToken: !GetAtt CreateTableLambdaFunction.Arn
        Version: 1.1

Outputs:
  qldbLedger:
    Value:
      Ref: qldbLedger
    Export:
      Name: iac-qldb-univo
  
  qldbstage:
    Vaulue: ${self:provider.stage}
    Export:
      Name: iac-qldb-univo-stage